server:
  port: 8100
spring:
  application:
    name: carmel-gateway
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  prefix: /olive
  routes:
    oauth2:
      path: /auth/**
      serviceId: olive-auth-server
    foudation-sevice:
      path: /api/**
      serviceId: olive-foundation-server
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


