server:
  port: 9999
spring:
  application:
    name: olive-carmel-gateway
zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie,Set-Cookie
  prefix: /olive
  routes:
    oauth2:
      path: /auth/**
      serviceId: olive-auth-server
    foudation-sevice:
      path: /api/**
      serviceId: olive-foundation-server
    sevice-registry:
      path: /registry/**
      serviceId: olive-sevice-registry  
    util-service:
      path: /util/**
      serviceId: olive-util-service  
proxy:
  auth:
    routes:
      api: oauth2
ribbon:
  eureka:
    enable: true
