server:
  port: 9004
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oliveFoundation?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect  
logging:
  level:
    root: info
    org:
      hibernate:
        type: info
        SQL: debug
    com:
      carmel:
        olive: trace

  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'

  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 5MB
  file:
    name: ./logs/olive-foundation-server.log


security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9002/oauth/check_token
    client:
      client-id: olive@carmelsolutions
      client-secret: P@ssw0rd
