server:
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oliveFoundation?createDatabaseIfNotExist=true
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect  
logging:
  level:
    root: info
    org:
      hibernate:
        type: info
        SQL: debug
    com:
      carmel:
        olive: trace

  pattern:
    console: '%d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\(%F:%L\) - %msg%n'

  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 5MB
  file:
    name: ./logs/olive-auth-server.log

#spring:
#  security:
#    user:
#      name: ronald
#      password: secret007
#      roles: ADMIN,USER
#
#security:
#  oauth2:
#    client:
#      client-id: mobile
#      client-secret: pin
#      access-token-validity-seconds: 3600
#      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
#      scope: READ,WRITE
#    authorization:
#      check-token-access: permitAll

carmel:
  getOliveRedirectURL : http://localost:9004


