server:
  port: 9001
spring:
  application:
    name: olive-service-registry
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
     serviceUrl:
      defaultZone: http://localhost:9001/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
